### ISSUE TITLE
Possible firmware issue

### ISSUE THREAD

**Issue by Lichthof** [nanpy/nanpy-firmware#20] opened 2016-02-03 20:13 UTC
I'm by no means an expert in the programming field, I've just started with an Arduino getting a speech synth chip to work. When trying to load some code that imports nanpy I get the following readout

E:\python>python serial.py
Traceback (most recent call last):
  File "serial.py", line 6, in <module>
    from nanpy import (arduinoapi, serial_manager)
  File "E:\Python 3.5.1\lib\site-packages\nanpy-0.9.5-py3.5.egg\nanpy\__init__.py", line 12, in <module>
  File "E:\Python 3.5.1\lib\site-packages\nanpy-0.9.5-py3.5.egg\nanpy\arduinoboard.py", line 1, in <module>
  File "E:\Python 3.5.1\lib\site-packages\nanpy-0.9.5-py3.5.egg\nanpy\serialmanager.py", line 3, in <module>
  File "E:\python\serial.py", line 6, in <module>
    from nanpy import (arduinoapi, serial_manager)
  File "E:\Python 3.5.1\lib\site-packages\nanpy-0.9.5-py3.5.egg\nanpy\arduinoapi.py", line 1, in <module>
ImportError: cannot import name 'arduinomethod'

The error is something to do with the arduinomethod(???) and I have no idea how I can fix the problem. Any help would be much appreciated.

**Comment by astagi** [comment] 2016-02-06 13:25
Looks like a problem with the python part. Nanpy-firmware must be flashed in the arduino board, Nanpy python part must be installed in your system or your virtual environment (more info here: http://nanpy.github.io/)

Try to install both of them and run some python example from here: https://github.com/nanpy/nanpy/tree/master/nanpy/examples

**Comment by Lichthof** [comment] 2016-02-06 14:21
I had already uploaded the firmware to the Arduino, and nanpy is installed on my PC. I've reinstalled them both and I'm still getting the same error. The examples create the same error too. It's probably something I'm doing wrong when installing something, but I can't see what it is that I'm doing wrong.

**Comment by astagi** [comment] 2016-02-06 19:13
Ok! Could you please show me the code of serial.py? I suppose this is a script you wrote and that is using Nanpy

**Comment by Lichthof** [comment] 2016-02-07 21:04
Sorry about the delay. This is the code I am using. http://pastebin.com/zH0AGC92

**Comment by astagi** [comment] 2016-02-07 21:21
No problem @Lichthof . The problem is that you're using old api, try with this example: http://pastebin.com/7haT2mXX

It should work! For more info: http://nanpy.github.io/

**Comment by Lichthof** [comment] 2016-02-07 22:04
I've tried that and now I'm getting this :(

Traceback (most recent call last):
  File "E:\python\serial.py", line 6, in <module>
    from nanpy import ArduinoApi, SerialManager
  File "E:\Python 3.5.1\lib\site-packages\nanpy\__init__.py", line 12, in <module>
    from nanpy.arduinoboard import ArduinoObject
  File "E:\Python 3.5.1\lib\site-packages\nanpy\arduinoboard.py", line 1, in <module>
    from nanpy.serialmanager import serial_manager
  File "E:\Python 3.5.1\lib\site-packages\nanpy\serialmanager.py", line 3, in <module>
    import serial
  File "E:\python\serial.py", line 6, in <module>
    from nanpy import ArduinoApi, SerialManager
ImportError: cannot import name 'ArduinoApi'
>>>

**Comment by astagi** [comment] 2016-02-07 22:45
Do you use Nanpy 0.9.5?

**Comment by Lichthof** [comment] 2016-02-07 22:48
Yes. I reinstalled twice using pip and easy_install, and both still create the same error.

**Comment by astagi** [comment] 2016-02-08 09:14
uhm really  weird.. please @Lichthof could you execute

    pip freeze | grep nanpy

and paste here the output?

**Comment by Lichthof** [comment] 2016-02-08 15:51
Here's the output:

e:\python>pip freeze Grep nanpy
nanpy==0.9.5
nltk==3.1
pyserial==3.0.1

**Comment by Lichthof** [comment] 2016-02-10 18:15
I've tried installing it all on my Surface Pro, and I'm still getting the same errors. :(

**Comment by ponty** [comment] 2016-02-11 15:36
try this:

```python
import nanpy
from pprint import pprint
pprint(nanpy.__dict__)
```

**Comment by Lichthof** [comment] 2016-02-11 20:16
This is the output - http://pastebin.com/2T0SNZyp

**Comment by ponty** [comment] 2016-02-12 07:38
Rename your script!

It has the same name as the `serial` module.

**Comment by Lichthof** [comment] 2016-02-12 10:37
Brilliant, thank you very much! But from one problem to another I'm now getting this :(

  File "E:\python\ssi.py", line 15, in <module>
    a1 = arduinoapi(connection=connection_1)
TypeError: 'module' object is not callable

**Comment by astagi** [comment] 2016-02-12 10:43
great catch @ponty :smile: 

@Lichthof please follow this example to use imported modules correctly https://github.com/nanpy/nanpy/blob/master/nanpy/examples/blink_2boards.py (or one of these example in the source https://github.com/nanpy/nanpy/blob/master/nanpy/examples/)

**Comment by astagi** [comment] 2016-02-13 08:46
@Lichthof can we close this issue?

**Comment by Lichthof** [comment] 2016-02-13 10:18
Yes! Thank you very much for your help and sorry it was such a silly problem!

**Comment by astagi** [comment] 2016-02-13 12:03
No problem @Lichthof :smile:

**Closed by astagi** 2016-02-13 12:03 UTC
